definitions:
  config:
    /hst:hst/hst:hosts/dev-localhost:
      .meta:residual-child-node-category: content
      jcr:primaryType: hst:virtualhostgroup
      hst:cmslocation: http://localhost:8080/cms
      hst:defaultport: 8080
      /localhost:
        .meta:residual-child-node-category: content
        jcr:primaryType: hst:virtualhost
        /hst:root:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:mount
          hst:homepage: root
          hst:mountpoint: /hst:hst/hst:sites/connect
          hst:pagemodelapi: resourceapi
          hst:showcontextpath: true
          /api:
            .meta:residual-child-node-category: content
            jcr:primaryType: hst:mount
            hst:alias: api
            hst:ismapped: false
            hst:namedpipeline: RestApiPipeline
            hst:types: [rest]
          /hst-api:
            .meta:residual-child-node-category: content
            jcr:primaryType: hst:mount
            hst:ismapped: false
            hst:namedpipeline: HstApiRestPipeline
            hst:responseheaders: ['Access-Control-Allow-Origin: *', 'Access-Control-Allow-Methods:
                GET,POST,PUT,DELETE,OPTIONS', 'Access-Control-Allow-Headers: Origin,X-Requested-With,Content-Type,Accept,Authorization']
            hst:types: [rest]
